
import type { Product } from './types';

export const BRANDS = ['titan', 'fastrack', 'Technoii', 'velocity', 'X-Ford', 'Lauredale Eyewear', 'NVG'] as const;
export const PRODUCT_TYPES = ['Frames', 'Lenses', 'Sunglasses', 'Contact Lenses'] as const;

export const PRODUCTS_DATA: Product[] = [
  {
    id: '1',
    name: 'Classic Aviator',
    description: 'Timeless aviator style with a modern twist. Perfect for any occasion.',
    price: 150.00,
    brand: 'fastrack',
    type: 'Sunglasses',
    imageId: 'classic-aviator',
    gender: 'Unisex',
  },
  {
    id: '2',
    name: 'Wayfarer Ease',
    description: 'The iconic Wayfarer, redesigned for a lighter, more comfortable fit.',
    price: 165.00,
    brand: 'titan',
    type: 'Sunglasses',
    imageId: 'wayfarer-ease',
    gender: 'Unisex',
  },
  {
    id: '3',
    name: 'Holbrook Prizm',
    description: 'A timeless, classic design fused with modern Oakley technology. Prizm™ lenses enhance color and contrast.',
    price: 195.00,
    brand: 'Technoii',
    type: 'Sunglasses',
    imageId: 'holbrook-prizm',
    gender: 'Men',
  },
  {
    id: '4',
    name: '714 Steve McQueen',
    description: 'The legendary folding sunglasses, famously worn by the "King of Cool".',
    price: 480.00,
    brand: 'velocity',
    type: 'Sunglasses',
    imageId: '714-steve-mcqueen',
    gender: 'Men',
  },
  {
    id: '5',
    name: 'Urban Lite Frames',
    description: 'Sleek, minimalist frames crafted from lightweight titanium. Ideal for everyday wear.',
    price: 220.00,
    brand: 'X-Ford',
    type: 'Frames',
    imageId: 'urban-lite-frames',
    gender: 'Unisex',
  },
  {
    id: '6',
    name: 'Chic Cat-Eye',
    description: 'A bold, vintage-inspired cat-eye frame that makes a statement.',
    price: 310.00,
    brand: 'Lauredale Eyewear',
    type: 'Frames',
    imageId: 'chic-cat-eye',
    gender: 'Women',
  },
  {
    id: '7',
    name: 'Sport Performance',
    description: 'Aerodynamic frames designed for high-performance sports and active lifestyles.',
    price: 210.00,
    brand: 'titan',
    type: 'Frames',
    imageId: 'sport-performance-frames',
    gender: 'Men',
  },
  {
    id: '8',
    name: 'ClearBlue Lenses',
    description: 'Advanced lenses with blue light filtering technology to reduce eye strain from digital screens.',
    price: 120.00,
    brand: 'Technoii',
    type: 'Lenses',
    imageId: 'clearblue-lenses',
  },
    {
    id: '9',
    name: 'Photochromic Lenses',
    description: 'Lenses that automatically darken when exposed to sunlight, providing seamless vision indoors and out.',
    price: 180.00,
    brand: 'velocity',
    type: 'Lenses',
    imageId: 'photochromic-lenses',
  },
  {
    id: '10',
    name: 'Polarized Pro',
    description: 'Top-tier polarized lenses that cut glare and enhance clarity for unparalleled visual comfort.',
    price: 250.00,
    brand: 'X-Ford',
    type: 'Lenses',
    imageId: 'polarized-pro-lenses',
  },
  {
    id: '11',
    name: 'Retro Round',
    description: 'Iconic round metal frames that capture a vintage, intellectual vibe.',
    price: 175.00,
    brand: 'fastrack',
    type: 'Frames',
    imageId: 'retro-round-frames',
    gender: 'Unisex',
  },
  {
    id: '12',
    name: 'Minimalist Square',
    description: 'Clean lines and a sophisticated square shape define these modern frames.',
    price: 350.00,
    brand: 'Lauredale Eyewear',
    type: 'Frames',
    imageId: 'minimalist-square-frames',
    gender: 'Unisex',
  },
  {
    id: '13',
    name: 'Stealth Blade',
    description: 'Futuristic shield-style sunglasses for a bold, high-fashion statement.',
    price: 295.00,
    brand: 'NVG',
    type: 'Sunglasses',
    imageId: 'stealth-blade',
    gender: 'Unisex',
  },
  {
    id: '14',
    name: 'Titanium Hexa',
    description: 'Modern hexagonal frames made from ultra-lightweight and durable titanium.',
    price: 420.00,
    brand: 'titan',
    type: 'Frames',
    imageId: 'titanium-hexa',
    gender: 'Women',
  },
  {
    id: '15',
    name: 'Oceanic Round',
    description: 'Stylish round sunglasses with a cool blue tint, perfect for beach days.',
    price: 185.00,
    brand: 'NVG',
    type: 'Sunglasses',
    imageId: 'oceanic-round',
    gender: 'Women',
  },
  {
    id: '16',
    name: 'Velocity Clubmaster',
    description: 'A retro and timeless design, the Clubmaster is a symbol of sophistication.',
    price: 280.00,
    brand: 'velocity',
    type: 'Frames',
    imageId: 'velocity-clubmaster',
    gender: 'Unisex',
  },
  {
    id: '17',
    name: 'Fastrack Sport Wrap',
    description: 'Wraparound sunglasses designed for maximum coverage during intense activities.',
    price: 130.00,
    brand: 'fastrack',
    type: 'Sunglasses',
    imageId: 'fastrack-sport-wrap',
    gender: 'Men',
  },
  {
    id: '18',
    name: 'X-Ford Browline',
    description: 'Classic browline glasses that offer a studious and distinguished look.',
    price: 265.00,
    brand: 'X-Ford',
    type: 'Frames',
    imageId: 'x-ford-browline',
    gender: 'Men',
  },
  {
    id: '19',
    name: 'Technoii Digital Lens',
    description: 'High-definition lenses optimized for digital screen usage, reducing fatigue.',
    price: 190.00,
    brand: 'Technoii',
    type: 'Lenses',
    imageId: 'technoii-digital-lens',
  },
  {
    id: '20',
    name: 'Lauredale Glam',
    description: 'Oversized and glamorous sunglasses for those who want to make an entrance.',
    price: 320.00,
    brand: 'Lauredale Eyewear',
    type: 'Sunglasses',
    imageId: 'lauredale-glam',
    gender: 'Women',
  },
  {
    id: '21',
    name: 'Titan Airflex',
    description: 'Extremely flexible and durable frames, designed for comfort and longevity.',
    price: 390.00,
    brand: 'titan',
    type: 'Frames',
    imageId: 'titan-airflex',
    gender: 'Kids',
  },
  {
    id: '22',
    name: 'NVG Night-Vision',
    description: 'Specialized lenses designed to reduce glare and improve clarity for night driving.',
    price: 230.00,
    brand: 'NVG',
    type: 'Lenses',
    imageId: 'nvg-night-vision',
  },
  {
    id: '23',
    name: 'Fastrack Urban',
    description: 'Trendy and affordable frames for the modern city dweller.',
    price: 95.00,
    brand: 'fastrack',
    type: 'Frames',
    imageId: 'fastrack-urban',
    gender: 'Kids',
  },
  {
    id: '24',
    name: 'Velocity Aviator II',
    description: 'A modern take on the classic aviator with updated materials and lens tech.',
    price: 210.00,
    brand: 'velocity',
    type: 'Sunglasses',
    imageId: 'velocity-aviator-2',
    gender: 'Unisex',
  },
  {
    id: '25',
    name: 'X-Ford Executive',
    description: 'Sophisticated and professional frames perfect for the office environment.',
    price: 330.00,
    brand: 'X-Ford',
    type: 'Frames',
    imageId: 'x-ford-executive',
    gender: 'Men',
  },
  {
    id: '26',
    name: 'Lauredale Tortoise',
    description: 'Classic tortoise-shell pattern on a chic, modern frame shape.',
    price: 290.00,
    brand: 'Lauredale Eyewear',
    type: 'Frames',
    imageId: 'lauredale-tortoise',
    gender: 'Women',
  },
  {
    id: '27',
    name: 'Titan Rimless',
    description: 'Ultra-lightweight rimless frames for a barely-there feel and a minimalist look.',
    price: 450.00,
    brand: 'titan',
    type: 'Frames',
    imageId: 'titan-rimless',
    gender: 'Unisex',
  },
  {
    id: '28',
    name: 'Technoii Drive Lens',
    description: 'Lenses with a specialized tint and polarization to enhance contrast while driving.',
    price: 260.00,
    brand: 'Technoii',
    type: 'Lenses',
    imageId: 'technoii-drive-lens',
  },
  {
    id: '29',
    name: 'NVG Shield Pro',
    description: 'Professional-grade shield sunglasses for maximum protection and a bold look.',
    price: 350.00,
    brand: 'NVG',
    type: 'Sunglasses',
    imageId: 'nvg-shield-pro',
    gender: 'Unisex',
  },
  {
    id: '30',
    name: 'Fastrack Gradient',
    description: 'Fashionable sunglasses with gradient lenses that are dark on top and lighter on the bottom.',
    price: 140.00,
    brand: 'fastrack',
    type: 'Sunglasses',
    imageId: 'fastrack-gradient',
    gender: 'Women',
  },
  {
    id: '31',
    name: 'Daily Comfort',
    description: 'Daily disposable contact lenses for maximum comfort and convenience.',
    price: 30.00,
    brand: 'Technoii',
    type: 'Contact Lenses',
    imageId: 'contact-daily-comfort',
  },
  {
    id: '32',
    name: 'Monthly Wear',
    description: 'Durable monthly contact lenses for consistent vision and comfort.',
    price: 25.00,
    brand: 'velocity',
    type: 'Contact Lenses',
    imageId: 'contact-monthly-wear',
  },
  {
    id: '33',
    name: 'Toric for Astigmatism',
    description: 'Specialized toric lenses to correct astigmatism for clear, stable vision.',
    price: 45.00,
    brand: 'X-Ford',
    type: 'Contact Lenses',
    imageId: 'contact-toric',
  },
  {
    id: '34',
    name: 'Multifocal Contacts',
    description: 'Multifocal lenses for clear vision at all distances, from near to far.',
    price: 55.00,
    brand: 'titan',
    type: 'Contact Lenses',
    imageId: 'contact-multifocal',
  },
  {
    id: '35',
    name: 'Color Contacts - Blue',
    description: 'Enhance your natural eye color with these vibrant blue contact lenses.',
    price: 35.00,
    brand: 'fastrack',
    type: 'Contact Lenses',
    imageId: 'contact-color-blue',
  },
];
