import type { Product } from './types';

export const BRANDS = ['Ray-Ban', 'Oakley', 'Persol', 'Gucci', 'Prada'] as const;
export const PRODUCT_TYPES = ['Frames', 'Lenses', 'Sunglasses'] as const;

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Classic Aviator',
    description: 'Timeless aviator style with a modern twist. Perfect for any occasion.',
    price: 150.00,
    brand: 'Ray-Ban',
    type: 'Sunglasses',
    imageId: 'classic-aviator',
  },
  {
    id: '2',
    name: 'Wayfarer Ease',
    description: 'The iconic Wayfarer, redesigned for a lighter, more comfortable fit.',
    price: 165.00,
    brand: 'Ray-Ban',
    type: 'Sunglasses',
    imageId: 'wayfarer-ease',
  },
  {
    id: '3',
    name: 'Holbrook Prizm',
    description: 'A timeless, classic design fused with modern Oakley technology. Prizm™ lenses enhance color and contrast.',
    price: 195.00,
    brand: 'Oakley',
    type: 'Sunglasses',
    imageId: 'holbrook-prizm',
  },
  {
    id: '4',
    name: '714 Steve McQueen',
    description: 'The legendary folding sunglasses, famously worn by the "King of Cool".',
    price: 480.00,
    brand: 'Persol',
    type: 'Sunglasses',
    imageId: '714-steve-mcqueen',
  },
  {
    id: '5',
    name: 'Urban Lite Frames',
    description: 'Sleek, minimalist frames crafted from lightweight titanium. Ideal for everyday wear.',
    price: 220.00,
    brand: 'Prada',
    type: 'Frames',
    imageId: 'urban-lite-frames',
  },
  {
    id: '6',
    name: 'Chic Cat-Eye',
    description: 'A bold, vintage-inspired cat-eye frame that makes a statement.',
    price: 310.00,
    brand: 'Gucci',
    type: 'Frames',
    imageId: 'chic-cat-eye',
  },
  {
    id: '7',
    name: 'Sport Performance',
    description: 'Aerodynamic frames designed for high-performance sports and active lifestyles.',
    price: 210.00,
    brand: 'Oakley',
    type: 'Frames',
    imageId: 'sport-performance-frames',
  },
  {
    id: '8',
    name: 'ClearBlue Lenses',
    description: 'Advanced lenses with blue light filtering technology to reduce eye strain from digital screens.',
    price: 120.00,
    brand: 'Oakley',
    type: 'Lenses',
    imageId: 'clearblue-lenses',
  },
    {
    id: '9',
    name: 'Photochromic Lenses',
    description: 'Lenses that automatically darken when exposed to sunlight, providing seamless vision indoors and out.',
    price: 180.00,
    brand: 'Persol',
    type: 'Lenses',
    imageId: 'photochromic-lenses',
  },
  {
    id: '10',
    name: 'Polarized Pro',
    description: 'Top-tier polarized lenses that cut glare and enhance clarity for unparalleled visual comfort.',
    price: 250.00,
    brand: 'Oakley',
    type: 'Lenses',
    imageId: 'polarized-pro-lenses',
  },
  {
    id: '11',
    name: 'Retro Round',
    description: 'Iconic round metal frames that capture a vintage, intellectual vibe.',
    price: 175.00,
    brand: 'Ray-Ban',
    type: 'Frames',
    imageId: 'retro-round-frames',
  },
  {
    id: '12',
    name: 'Minimalist Square',
    description: 'Clean lines and a sophisticated square shape define these modern frames.',
    price: 350.00,
    brand: 'Prada',
    type: 'Frames',
    imageId: 'minimalist-square-frames',
  },
];
